# Generated by Django 4.2.7 on 2023-12-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0002_rename_category_book_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='book',
            name='categories',
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.CharField(default='', max_length=100),
        ),
    ]
