# Generated by Django 4.2.7 on 2023-12-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0003_remove_book_authors_remove_book_categories_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='categories',
            new_name='category',
        ),
    ]
