# Generated by Django 4.2.7 on 2024-01-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0005_remove_author_name_remove_publisher_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='address',
        ),
    ]
