# Generated by Django 4.2.7 on 2024-01-07 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_manager', '0006_remove_author_first_name_remove_author_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='author_name',
            new_name='name',
        ),
    ]
